version: '3.8'

services:
  # Postgres database service
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    network_mode: "host"  # Use host network

  # Backend service
  backend:
    build:
      context: .
      dockerfile: ${BACKEND_DOCKERFILE}  # Ensure the production Dockerfile handles building for production
    container_name: histori-backend
    environment:
      NODE_ENV: production  # Set to production
    depends_on:
      - db
    volumes:
      # You might not want to mount local volumes in production, so this is optional:
      # - .:/usr/src/backend
      # If needed, you can add a volume for persistent data storage
      - /usr/src/backend/node_modules
    network_mode: "host"  # Use host network

volumes:
  postgres-data:
