version: '3.8'

services:
  # Postgres database service
  histori-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # Expose PostgreSQL on port 5433 for external connections

volumes:
  postgres-data: