version: '3.8'

services:
  # Postgres database service
  histori-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # Expose PostgreSQL on port 5433 for external connections

  # Backend service
  histori-backend:
    build:
      context: .
      dockerfile: ${BACKEND_DOCKERFILE}
    container_name: histori-backend
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@histori-db:5432/${POSTGRES_DB}  # Internal connection string for the database
    depends_on:
      - histori-db
    ports:
      - "4242:4242"  # Expose port 4242 for external connections
    volumes:
      - .:/usr/src/backend
      - /usr/src/backend/node_modules

volumes:
  postgres-data: